### ISSUE TITLE
Capture environment / generate diagnostics bundle

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#114]
There needs to be a simple, push-button method to generate a diagnostics bundle that users are able to provide to the project's developers when encountering a problem. From the server side this might be a resource at `/help` that generates a tarball with libStorage logs, merged configuration information, and other helpful insight into the system.

This use case should also introduce a new function to be implemented by Storage Drivers, `Help() (chan string, error)`. This function should return a channel on which will be received a path to a directory or file (it's up to the channel reader to determine which) that is either an asset or a directory of assets to be included in the generated support bundle. This provides driver developers the ability to be engaged in the diagnostics bundle generation process as they know better than the libStorage framework developers what information is relevant to a specific driver.

**Comment by clintonskitson** [comment]
This is a great idea @akutz.
