### ISSUE TITLE
EC2 Tagging

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#126]
Hi @clintonskitson,

What are your thoughts on keeping/renaming the _REX-Ray Tag_ in the libStorage port of `REX-Ray`'s ec2 driver. For example, I started a **very** **preliminary** port of the EC2 driver this afternoon, and while I might work on it some more later today, already I ran into an interesting issue -- the concept of the `REX-Ray` tag introduced in `REX-Ray`'s 0.3.3 release. In libStorage it looks like this at lines [9-10](https://github.com/akutz/libstorage/blob/feature/ec2/drivers/storage/ec2/ec2.go#L9-10) and [56-59](https://github.com/akutz/libstorage/blob/feature/ec2/drivers/storage/ec2/ec2.go#L56-L59) of `./drivers/storage/ec2/ec2.go`:

```
    // REXRatTag is the name of the EC2 tag.
    REXRayTag = "rexraySet"
```

```
// REXRayTag returns the AWS REX-Ray tag.
func REXRayTag(config gofig.Config) string {
    return config.GetString("aws.rexrayTag")
}
```

However, should we rename it? I honestly don't care either way. I can see arguments for changing the name as it hasn't been around that long; I can see the argument for keeping it to maintain backwards compatibility.

Thoughts? @kacole2, how about yourself? What do you think @echupriyanov? After all, you're the one who originally created the tagging in [`REX-Ray` PR #358](https://github.com/emccode/rexray/pull/358).

**Comment by akutz** [comment]
Hi @clintonskitson, @kacole2, @echupriyanov,

Any feedback?

**Comment by echupriyanov** [comment]
@akutz 

REXRayTag was introduced to limit volume/snapshot listings to contain only objects managed by RexRay.
As libStorage is more general framework, I think that instead of fixed tag you can add `labels` parameter to volumes/snapshots and let higher level to set/use them as filter.

**Comment by akutz** [comment]
Hi @echupriyanov,

Thank you for the feedback! Would you like to see the EC2 driver port completed and then you notified so you can take a stab at a labelling mechanism?

**Comment by echupriyanov** [comment]
@akutz 

Thanks for the offer. I’ll be happy to take a look and try to implement it.

**Comment by akutz** [comment]
Hi @echupriyanov,

It's no where near a complete driver yet, but I will ping you once I've completed the port. Thanks!

**Comment by clintonskitson** [comment]
@akutz Here is another one to check out.

https://github.com/emccode/rexray/issues/405

**Comment by codenrhoden** [comment]
Closing in deference to #456
