### ISSUE TITLE
Server-side inner-issues squashed if stdlib `errors` library used

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#128]
At first it seemed like a regression, because when dealing with the VBox driver I noticed that despite all the work in #98, it appeared server-side errors with inner-errors were once again being squashed. It turns out, they are, but only if the inner-errors are produced via Golang's stdlib `errors` package since the struct behind the stdlib `Error` interface has no public, exported fields that are marshaled to JSON.

To reproduce the issue I added the following to the top of the VFS driver's `VolumeAttach` function:

```
func (d *driver) VolumeAttach(
    ctx types.Context,
    volumeID string,
    opts *types.VolumeAttachOpts) (*types.Volume, string, error) {

    iid := context.MustInstanceID(ctx)
    if iid != nil {
        return nil, "", goof.WithFieldE(
            "path", "/tmp", "this error has an inner error",
            goof.New("a bug squashing expedition all died"))
    }
```

The above works just fine, printing out the inner error to the server-side log and the HTTP response:

```
INFO[0001] executing task                                host=tcp://127.0.0.1:50451 instanceID=vfs=pax.kutz server=pine-hound-tk service=vfs task=0 tls=false txCR=1463191276 txID=a6acd8a4-57ea-4095-479c-b91d9816cdce
ERRO[0001] this error has an inner error                 host=tcp://127.0.0.1:50451 inner=msg="a bug squashing expedition all died" instanceID=vfs=pax.kutz path=/tmp server=pine-hound-tk service=vfs task=0 tls=false txCR=1463191276 txID=a6acd8a4-57ea-4095-479c-b91d9816cdce
```

```
INFO[0001]     -------------------------- HTTP RESPONSE (SERVER) ------------------------- 
INFO[0001]     Content-Type=application/json            
INFO[0001]                                              
INFO[0001]     {                                        
INFO[0001]       "message": "this error has an inner error", 
INFO[0001]       "status": 500,                         
INFO[0001]       "error": {                             
INFO[0001]         "inner": "a bug squashing expedition all died", 
INFO[0001]         "path": "/tmp"                       
INFO[0001]       }                                      
INFO[0001]     }
```

However, if the inner error is changed so that it's created by the stdlib `errors` package, it is maintained in the server-side error log but lost in translation on the HTTP response to the client:

```
func (d *driver) VolumeAttach(
    ctx types.Context,
    volumeID string,
    opts *types.VolumeAttachOpts) (*types.Volume, string, error) {

    iid := context.MustInstanceID(ctx)
    if iid != nil {
        return nil, "", goof.WithFieldE(
            "path", "/tmp", "this error has an inner error",
            errors.New("a bug squashing expedition all died"))
    }
```

```
INFO[0001] executing task                                host=tcp://127.0.0.1:22765 instanceID=vfs=pax.kutz server=flower-raccoon-kg service=vfs task=0 tls=false txCR=1463191338 txID=32d5411f-0f31-4605-51d1-7f302390c7c9
ERRO[0001] this error has an inner error                 host=tcp://127.0.0.1:22765 inner=a bug squashing expedition all died instanceID=vfs=pax.kutz path=/tmp server=flower-raccoon-kg service=vfs task=0 tls=false txCR=1463191338 txID=32d5411f-0f31-4605-51d1-7f302390c7c9
```

```
INFO[0001]     -------------------------- HTTP RESPONSE (SERVER) ------------------------- 
INFO[0001]     Content-Type=application/json            
INFO[0001]                                              
INFO[0001]     {                                        
INFO[0001]       "message": "this error has an inner error", 
INFO[0001]       "status": 500,                         
INFO[0001]       "error": {                             
INFO[0001]         "inner": {},                         
INFO[0001]         "path": "/tmp"                       
INFO[0001]       }                                      
INFO[0001]     }  
```

It seems like the libStorage HTTP error handler will need to check if all errors are goofs, and if so, recurse into all possible inner errors and make sure they too are wrapped with goof error types in order to ensure that inner error information is not lost.

(cc @clintonskitson)

**Comment by clintonskitson** [comment]
Interesting, good find. Glad to be able to move in the right direction here for logging. In doing the drivers I did test that we were getting the init errors successfully.

**Comment by akutz** [comment]
Hi @clintonskitson,

Specifically for VBox we aren't though. Even [in the `Init` method](https://github.com/emccode/libstorage/blob/master/drivers/storage/vbox/storage/vbox_storage.go#L59-L62), it's returning an inner-error from the [VBox Client Logn function](https://github.com/clintonskitson/go-virtualboxclient/blob/e0978ab2ed407095400a69d5933958dd260058cd/virtualboxclient/virtualbox.go#L74-L88), and if it's like all the other errors returned from that package, it's a stdlib error, and will be squashed.

**Comment by akutz** [comment]
For VBox, and others, the solution is to create a new Goof error from any error where all we know about said error is that it's the `Error` interface. In that cause wrap it with `goof.New(innerErr.Error())`. That will create a new Goof error with the same message as the one that could just be a stdlib error -- a struct sans exported field that will marshal to JSON as empty.

**Comment by akutz** [comment]
For the Vbox driver at least I will go through and make sure all errors

**Comment by akutz** [comment]
Hi @clintonskitson,

What I'll likely do is update Goof so that it includes two new features:

1. A function called `Newe(err Error)` that behaves like `New` and `Newf`, taking an existing error, instead of a string or format string and args, and creating a Goof error out of it.

2. A function called `Inner(err Error)` which will inspect the provided error, and if it's a Goof error check if there is an inner error. It will then check the inner error to see if *it's* a Goof error, and if not, invoke `Newe` on it. If it *is* a Goof error, it will invoke `Inner` on it.

I'll also make sure `Inner` is invoked any time a new Goof error is created with an inner error.

Finally I'll update the libStorage HTTP error handler to invoke `goof.Inner` on any errors before they're marshaled to JSON. That should take care of the possibility of us losing error information.

**Comment by clintonskitson** [comment]
Wicked. Would be great to be able to put the issue to bed.

**Comment by vladimirvivien** [comment]
@akutz do you recall if `goof` was ever changed to implement your suggestions above?

**Comment by akutz** [comment]
Hi @vladimirvivien, 

It does not appear so. Care to file a PR? If you lack time I will do this later this week.

**Comment by akutz** [comment]
HI @vladimirvivien,

I have submitted akutz/goof#5 to handle the aforementioned error enhancements to Goof.
