### ISSUE TITLE
Enable VFS to perform bind mounts

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#132]
Being able to perform actual attaches/detaches using the integration driver would make end-to-end testing simpler in CI platforms. I believe what would be needed to properly simulate this would be to work on the `Mount` operation to ensure that we can do bind mounts.

@akutz has discussed this before where we would use loopback devices. I believe the bind mount may be a more universal approach? Nonetheless a fuller functioning VFS drivers would be helpful.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #945](https://github.com/codedellemc/rexray/issues/945) via [**ZenHub**](https://www.zenhub.com/)
