### ISSUE TITLE
Refactor the test harness

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#133]
In collaboration, or even in replacement, of #131, the `./test` package should be refactored to be the one-stop shop for all testing at the CI level. The test package should essentially start a libStorage server with all available remote storage drivers and then perform end-to-end workflows that involve each of the storage drivers as well as the integration and OS driver. The storage drivers should register themselves with the test package, providing expected results in the form of JSON that can be unmarshalled to the expected result types for each of the pre-defined tests.

An example would be:

```
func TestVolumeLifecycle(t *testing.T) {


    client, err := New(...

    client.Integration.Create(...

    client.Integration.Attach(...

    client.Integration.Mount(...

    client.Integration.Unmount(...

    client.Integration.Remove(...
}
```

The above lifecycle test will cover not only much of the integration driver, but involve the storage and OS drivers well. It's wasteful to continue to reimplement the same workflow tasks as tests for each individual driver when the purpose of libStorage is to bring these disparate parts together and have them work in concert with one another. Of course there is still the need for unit testing at a more granular level such as the tests in `./api/types` or `./api/utils/semaphores`, and there always will be. However, testing the drivers themselves should happen as a global act and not on a per-driver basis.

@clintonskitson, thoughts?

**Comment by clintonskitson** [comment]
@akutz Yes I do agree. I think there should be a single package for testing driver packages. I feel like this should still be separate from the integration level testing.

Definitely moving in the right direction.

**Comment by akutz** [comment]
Nah, the direction is fine, you're just holding the map sideways. There will be a single test harness as I described, but never did I say that it was necessary to use it to test all drivers at once. On systems that support it we will test more than one storage driver at once, and on others we will be restricted to testing specific drivers as supported by the platform on which the test harness is executed.

Regarding how testing will proceed for storage and integration drivers, the he tests will encompass them both.

One could say the tests will "integrate" various aspects of our product and test them together, as a single, cohesive unit.

Hmmm, if only there was a name for such a test process where you integrate different components to test them in concert? A concert test? A component togetherness test? I know! How about integration testing!

So yes, the planned direction for the test harness is fine. If there is any more cartographic confusion, I'll be happy to clear it up.

-- 
-a
