### ISSUE TITLE
Enhanced volume retrieval queries

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#153]
The volume retrieval mechanism could be made more efficient for certain types of queries. 

Today to retrieve a single volume instance by name, List() occurs to retrieve that specific volume. It would be great to include a query based capability to `volumes` to allow an efficient lookup based on name.

Today when looking for a set of volumes, a list operation must be used. If using the middleware, this list is then filtered before it ends up at the libstorage client. However, this still may be more heavy lifting than required. A list request should be able to send a list of valid volumeID's to be returned, which would additionally pass through the middleware. 

In both these instances, the driver implementation may be able to provide efficient means to return either a) a subset of multiple volumes at one time that are requested b) a return of a volume by name.

**Comment by akutz** [comment]
Hi @clintonskitson,

How big of a deal is this? We could totally get it in for 0.1.1 with not a terrible amount of effort due to the existence of filtering already. I'd just need to add the code that latches onto the filtering already present.

**Comment by clintonskitson** [comment]
@akutz I believe it might be more work than you're thinking. There are two distinct things covered

1) The driver itself should be able to pass back a volume based on the name versus returning everything and having that list filtered. 
2) The /volumes path should be able to receive a query for specific volume ids. This should then also be passed down to the driver to be able to implement in an efficient means if possible.

Was that your understanding?

**Comment by akutz** [comment]
Yes.

1) This exists today, but no driver author chose to take advantage of it. It's up to the driver's author to check for the existence of a filter and then to construct storage platform-specific logic/queries based on said filter in order to provide native filtering.

2) The existing filter logic would be extended to look for ID constraints in addition to name constraints.

**Comment by clintonskitson** [comment]
Following up to this conversation. To get the highest scalability for the plugins, this needs to be addressed in the current and planned drivers that are a part of 0.1.3.

**Comment by clintonskitson** [comment]
https://github.com/emccode/libstorage/issues/130
