### ISSUE TITLE
Add new volumes capabilities method

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#178]
Docker PR https://github.com/docker/docker/pull/22077

The Docker 1.12 Volume API includes a new primitive for declaring the scope of the reported volumes. These can either be `local` or `global`. This should be a configurable option in libStorage and defaulted to `global`.

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/blob/master/daemon/module/docker/volumedriver/voldriver.go#L215-L219
