### ISSUE TITLE
Add OpenStack storage driver

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#182]
This issue is capturing the future place for the introduction of the OpenStack driver.

This driver will include existing functionality from REX-Ray and enhanced for.
- RackSpace support in this driver
- Awareness of Xen/KVM for different discovery mechanics
- Updated discovery logic

**Comment by justinclayton** [comment]
@clintonskitson I've got additions to the openstack storage driver from [emccode/rexray](https://github.com/emccode/rexray) that have been made against v0.3.3. The branch is here: [openstack_volume_attach_fix](https://github.com/justinclayton/rexray/tree/openstack_volume_attach_fix). There's not even a release branch for v0.3.3 anymore so I can't even make a PR against it at the moment. How should I proceed?

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/issues/246#issuecomment-225804117

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/issues/368

**Comment by kacole2** [comment]
https://github.com/emccode/rexray/issues/489

**Comment by strigazi** [comment]
Support for authentication with trust users added in gophercloud. [1]

We want to use rexray to mount cinder volumes on a docker swarm cluster and currently we must pass the username/password credentials to the hosts of the cluster. The best option would be to authenticate with the trustee's credentials.

[1] https://github.com/rackspace/gophercloud/pull/580

**Comment by MatMaul** [comment]
I am currently working on this, beginning by a port of the rexray 0.3.x driver. I just saw that @akiraw is assigned, but the current code in your libstorage fork seems to be mainly a stub. You can see my WIP here (not working yet) : https://github.com/MatMaul/libstorage

**Comment by MatMaul** [comment]
And it is now working :)

Tested with standalone commands and with the docker integration.
I'll send a PR tomorrow.

**Comment by akailash** [comment]
Will this be released soon?

**Comment by kacole2** [comment]
@akailash please follow here -> https://github.com/codedellemc/libstorage/pull/536

**Comment by codenrhoden** [comment]
Closed by #536
