### ISSUE TITLE
Volume map updates

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#184]
This is a placeholder for future changes being introduced for the volume mapping logic from @akutz.
- All Volumes no attachments
- All Volumes with attachments
- All Volumes with attachments to me
- A volume with no attachments
- A volume with attachments
- A volume with attachments to me
  .. a set of volumes

**Comment by codenrhoden** [comment]
This went in over a series of PRs, namely #316 and #327, with bugfixes in others.
