### ISSUE TITLE
Containerization primitives and driver updates

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#185]
Another valid opportunity for running the plugins is that they are operated from containers by container platforms as dependent or prioritized services. This is also important for those that want to embed libStorage functionality where the service ends up running inside of a container. Although the service could still work today, it requires different configuration of the container based on which driver is being used.

The largest challenge here is that each of the drivers typically requires access to certain tools or paths to work with devices. This can be simplified dramatically by introducing a configurable option like `containerPath` which would be absorbed by the drivers to ensure any FS related activities take place from that path onwards.

This would ensure `docker run -ti -v /:/rootfs -e LIBSTORAGE_CONTAINERPATH=/rootfs libstorage` would work without needing to know specifics about plugins.

More details of course..

**Comment by codenrhoden** [comment]
I'm calling this done with the Docker 1.13 plugins. reopen if disagree.
