### ISSUE TITLE
Add vSphere driver

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#190]
This issue is tracking the addition of the vSphere driver.

**Comment by codenrhoden** [comment]
@cduchesne Does this need to stick around? Is this on the roadmap? I'm inclined to close.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #947](https://github.com/codedellemc/rexray/issues/947) via [**ZenHub**](https://www.zenhub.com/)
