### ISSUE TITLE
Add Ceph storage driver

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#191]
This issue is tracking the addition of the Ceph driver.

**Comment by lhoss** [comment]
👍  for getting a ceph driver
this should be very useful for people/companies that want to build a distributed storage solution, with purely open source, but without openstack/cinder!

**Comment by tobilg** [comment]
Any updates un this? Thanks in advance!

**Comment by a-nldisr** [comment]
Hello, 
Recently RedHat added the rbd storage driver to Kubernetes, perhaps the code could give some guidelines how to implement this in Rexray. I am not the author of this code, but during a talk with a Rexray member at the Mesoscon the EMCcode member mentioned that code examples were welcome. 

https://github.com/kubernetes/kubernetes/pull/31251

**Comment by codenrhoden** [comment]
@a-nldisr Thanks for the heads up. I will be working on the Ceph driver very soon, and I will be sure to take a look at what was done in k8s.

**Comment by tobilg** [comment]
An ETA on this? Thanks!

**Comment by cduchesne** [comment]
@tobilg - We are actively working on it and the progress can be seen https://github.com/codedellemc/rexray/issues/527 and https://github.com/codenrhoden/libstorage/tree/feature/rbd.

We are targeting the first few weeks of December for release

**Comment by codenrhoden** [comment]
Ceph RBD driver is available in v0.4.0. https://github.com/codedellemc/libstorage/releases/tag/v0.4.0
