### ISSUE TITLE
Introduce leader election capabilities

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#194]
Leader election can be beneficial for ensuring HA for control plane calls to storage platforms. Introducing this at a libStorage level can be an important natural benefit of adopting libStorage and introducing new implementation of libStorage that may sit in front of storage platforms (Polly).

**Comment by codenrhoden** [comment]
Is running a clustered set of libStorage servers on the roadmap, @cduchesne ? If not, let's close this until it is.
