### ISSUE TITLE
Add Digital Ocean storage driver

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#197]

**Comment by kacole2** [comment]
Digital Ocean just announced support for block storage. https://www.digitalocean.com/company/blog/block-storage-more-space-to-scale/

**Comment by kacole2** [comment]
the API - https://developers.digitalocean.com/documentation/v2/#block-storage

**Comment by kacole2** [comment]
storage is supported in the DO Golang API Client. https://github.com/digitalocean/godo

**Comment by vladimirvivien** [comment]
@clintonskitson phychic

**Comment by protochron** [comment]
I started working on a driver for this: https://github.com/protochron/libstorage/tree/digitalocean_volumes

I'm hoping to have a PR ready in the next week or two :D

**Comment by cduchesne** [comment]
This is great Dan! We're excited to see the PR come through. Don't hesitate to reach out if you run into any issues or have any questions.

**Comment by vfarcic** [comment]
@protochron Do you have an ETA on DO?

**Comment by protochron** [comment]
@vfarcic I'm working on shoring up tests and making sure everything is working, so figure before the end of the year? Real life got in the way of getting this out as quickly as I would have liked unfortunately :(

**Comment by vfarcic** [comment]
@protochron Any progress on this one?

**Comment by protochron** [comment]
@vfarcic working through some of the final changes for #392

**Comment by kacole2** [comment]
@cduchesne @clintonskitson can we close this out?

**Comment by cduchesne** [comment]
Yes, had been tracking #392. Closing this one as #392 is merged
