### ISSUE TITLE
Builds using a Docker container should be supported

### ISSUE THREAD

**Issue by akiraw** [codedellemc/libstorage#207]
It would be a great convenience if builds could be performed using a standardized published Dockerfile

**Comment by akutz** [comment]
Does the Makefile not work for you? Is there a problem with the current process that you're able to illuminate here?

**Comment by vaibhavkhanduja** [comment]
-1
Makefile build went very fine for me .. won't prefer Dockefile

**Comment by codenrhoden** [comment]
I think this can be closed...

Building with Docker went in over a month ago: 8164e2d6624efbe2475eb3c1adbd9b41c8de8eab

It is the default, but a simple `make deps && make build` will still function as before, without Docker. So @vaibhavkhanduja you can still build as before.
