### ISSUE TITLE
Add Client Type Documentation

### ISSUE THREAD

**Issue by Oskoss** [codedellemc/libstorage#209]
Docs need to be updated to explain client types.

Thanks!

**Comment by akutz** [comment]
Hi @Oskoss,

You're absolutely correct. How long do you think it will take you to put together a PR for that? ;)

**Comment by Oskoss** [comment]
Sure! eta 1 day 👍

**Comment by Oskoss** [comment]
@akutz Also working on a PR to fix mounting volumes to multiple different hosts in the docker integration driver.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #950](https://github.com/codedellemc/rexray/issues/950) via [**ZenHub**](https://www.zenhub.com/)
