### ISSUE TITLE
Scaleio Driver tests should skip by deafult

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/libstorage#235]
The ScaleIO driver requires the storage service to be running.  This may not be true in all setup (i.e. CI).  Currently the test for scaleio defaults to running.  It looks like the logic to skipping the test is reverse.  The following will return `false` by default when both of these env vars are not explicitly set.  Instead, the test should be skipped by default unless `TEST_SCALEIO` is set.

```
func skipTests() bool {
    travis, _ := strconv.ParseBool(os.Getenv("TRAVIS"))
    noTest, _ := strconv.ParseBool(os.Getenv("TEST_SKIP_SCALEIO"))
    fmt.Println("*** Skipping Test ? ****", travis || noTest)
    return travis || noTest
}
```

**Comment by codenrhoden** [comment]
I think this is mostly a misunderstanding of the test binary is meant to be used. You compile the binary, then copy it to a place where it can be run successfully. In that sense, it should run by default. The env vars that allow it to be skipped are mostly to ensure that it is skipped by default _on Travis-CI_, or if you explicitly force it to skip for any reason.

But it's not intended for someone to make and run all the tests at once. So I think it's still reasonable that the tests in a given test binary run by default.
