### ISSUE TITLE
Add FibreChannel support for XtremIO driver

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/libstorage#239]
FibreChannel is commonplace in XtremIO implementations. We should support FibreChannel as well as iSCSI with our XtremIO driver and we should treat the implementation similarly to other drivers that support FibreChannel, such as VMAX.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #951](https://github.com/codedellemc/rexray/issues/951) via [**ZenHub**](https://www.zenhub.com/)
