### ISSUE TITLE
Update to use package akutz/gofig that 

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/libstorage#249]
This is TODO marker to update to proper ref commit id once https://github.com/akutz/gofig/issues/10 is done.  This transitions from using burntsushi/toml to pelletier/go-toml (see
https://github.com/spf13/viper/commit/7fb2782df3d83e0036cc89f461ed0422628776f4)

**Comment by codenrhoden** [comment]
This was taken care of with b2be18e8c1c9039710d3fc54b6e91bde324e36f7
