### ISSUE TITLE
Update libstorage documentation to reflect new company name

### ISSUE THREAD

**Issue by jonasrosland** [codedellemc/libstorage#262]
The team name is now "{code} by Dell EMC" instead of "EMC {code}"

**Comment by codenrhoden** [comment]
Ha - I notice that even today both rexray and libS RTD have an EMC {code} reference in the nav header, all the way on the right, that link to a github.io page. Still needs fixed! Surprised we've missed that.

**Comment by koensayr** [comment]
Perhaps this issue is a duplicate?

**Comment by akutz** [comment]
Closing.
