### ISSUE TITLE
Docker's Integration Driver doesn't Respect Wait Failure

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#266]
The Docker integration driver [doesn't care](https://github.com/emccode/libstorage/blob/master/drivers/integration/docker/docker.go#L218) if the wait operation that occurs after a volume attach call times out without a match:

> ```
>             _, _, err = client.Executor().WaitForDevice(ctx, opts)
>             if err != nil {
>                 return "", nil, goof.WithError(
>                     "problem with device discovery", err)
>             }
> ```

If the wait op times out then the integration driver should likely return an error saying that the Mount function could not complete successfully.

(cc @proudh)

**Comment by akiraw** [comment]
After discussing with @proudh, we settled on this small change:

wait, _, err = client.Executor().WaitForDevice(ctx, opts)
if err != nil {
      return "", nil, goof.WithError("problem with device discovery", err)
}
if !wait {

}

is this what you had in mind?

**Comment by akiraw** [comment]
After discussing with @proudh , we settled on this small change:

`wait, _, err = client.Executor().WaitForDevice(ctx, opts)`
`if err != nil {`
      ` return "", nil, goof.WithError("problem with device discovery", err)`
`}`
`if !wait {`
     `return "", nil, goof.New("wait for device timed out")`
`}`

is this what you had in mind?
