### ISSUE TITLE
Openstack : CACERT ?

### ISSUE THREAD

**Issue by davvdg** [codedellemc/libstorage#272]
Hi, to access my private openstack cloud with openstack cli I need to provide a (path to a) certificate through the OS_CACERT env. How should I configure that in rexray and is it handled ?

Thanks

David

**Comment by codenrhoden** [comment]
something to check along with #182 and #243

**Comment by MatMaul** [comment]
It doesn't look like it is supported by gophercloud with an explicit option. However it is possible that we could override an http client somewhere to do so, to be checked.

**Comment by olivibernard** [comment]
Hi there,
Is this available in release 0.9.0 ?
I have the same request : how to configure rexray/cinder and specify openstack certs ?
Thanks

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #952](https://github.com/codedellemc/rexray/issues/952) via [**ZenHub**](https://www.zenhub.com/)
