### ISSUE TITLE
VolumeInspect crashes for some drivers if no volume is found (nil deref)

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/libstorage#396]
Hey @akutz, I need your expertise on what the right way to fix this is...

I noticed that if `VolumeInspect` returns `nil, nil`, the framework crashes with a nil deref. Is it always expected that the returned volume will be non-nil if `err != nil`? Put another way, if the volume is not found, should we return an error?

The drivers are not consistent about this. When I'm writing new drivers, I've been looking mostly at EBS and ScaleIO as guides, but they take different approaches.

EBS: (https://github.com/codedellemc/libstorage/blob/master/drivers/storage/ebs/storage/ebs_storage.go#L273-L275)
```
	if len(ec2vols) == 0 {
		return nil, errNoVolReturned
	}
```

ScaleIO (https://github.com/codedellemc/libstorage/blob/master/drivers/storage/scaleio/storage/scaleio_storage.go#L273-L275)
```
	if len(volumes) == 0 {
		return nil, nil
	}

```

If I'm reading things correctly, the ScaleIO driver would crash if you did an InstanceInspect on a non-existing volume. Or perhaps it doesn't because the underlying API returns an error, which gets caught first, and in that case the code I'm referencing is dead code. Either way, it's confusing.  Here is a partial backtrace of the crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bbdb6]

goroutine 29 [running]:
panic(0xab3300, 0xc4200140b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/codedellemc/libstorage/api/server/router/volume.handleVolAttachments(0xed9200, 0xc42004b800, 0x0, 0xc420294680, 0x0, 0x0, 0x0)
        /go/src/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:139 +0x446
github.com/codedellemc/libstorage/api/server/router/volume.(*router).volumeInspect.func2(0xed9200, 0xc42004b800, 0xed3740, 0xc42019ce00, 0xc42035d270, 0xc420297e00, 0xb95802, 0xc)
        /go/src/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:353 +0x178
```

The line numbers match up fine with the current `master`, and it is simply because `InstanceInspect` returns `nil,nil`.

Super easy fix whichever direction we go, just need your guidance.

Depending on your answer, I'm happy to fix this either by correcting the drivers (where necessary), or adding a check in volume_routes to check for nil.

**Comment by codenrhoden** [comment]
It's also worth nothing that I had seen disparate behavior in `Volumes` as well (but no crashes so far), and had noted that I wanted to come back and figure out the desired way to handle it:

https://github.com/codenrhoden/libstorage/blob/feature/gce/drivers/storage/gce/storage/gce_storage.go#L219-L223

**Comment by akutz** [comment]
If no object is discovered an error should def be returned.
