### ISSUE TITLE
local device lookup does not work in client/server mode

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/libstorage#432]
The digital ocean driver is assuming its running on the same node as the client. This causes local device maps to fail.

This is best evidenced by this: https://github.com/codedellemc/libstorage/blob/release/0.5.0/drivers/storage/digitalocean/storage/digitalocean_storage.go#L318-L323

When it tries to look up the device name, it’s looking at the local file system instead of the local Device map supplied by the client.

If this driver is really going into 0.5, we'll need to document that it does not work for client/server deployments, and that preemption does not work (because of #431).

**Comment by akutz** [comment]
This is interesting because FittedCloud had made the same error. Clearly we need to do a better job with a driver template to explain the workflow.

**Comment by akutz** [comment]
Also, I spoke with Dan about his driver. He seemed very aware of the workflow; this is surprising. I do not think it will be too difficult to fix though. Maybe you or I can patch it if Dan does not have time.

**Comment by protochron** [comment]
That's on me. `toTypesVolume` is fairly old with respect to the rest of the driver, so it predated fully understanding the workflow. Having a driver template that shows what the workflow looks like would definitely help!
