### ISSUE TITLE
Provide FittedCloud documentation 

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#437]
Hi @jack-fittedcloud,

Can you please add documentation for the driver ASAP? Thank you!

**Comment by jack-fittedcloud** [comment]
Hi @akutz,

Could you point out which files and examples so I can work on?  Thanks!

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

Sure thing. The rendered documentation looks like [this](http://libstorage.readthedocs.io/en/release-0.5.0/user-guide/storage-providers). The source is [here](https://github.com/codedellemc/libstorage/blob/release/0.5.0/.docs/user-guide/storage-providers.md).
