### ISSUE TITLE
Ceph Kraken/RBD causes Go panic

### ISSUE THREAD

**Issue by srhb** [codedellemc/libstorage#451]
# Summary
When using ceph-common from the Kraken release instead of eg. Jewel, a go panic arises whenever image status is probed. I assume the problem is in libstorage (but I may be mistaken...) since that is where the go panic arises.

    REX-Ray
    -------
    Binary: /usr/bin/rexray
    Flavor: client+agent+controller
    SemVer: 0.8.1
    OsArch: Linux-x86_64
    Branch: v0.8.1
    Commit: 30e9082dd9917f0d218ca981f886d701110ce5f5
    Formed: Sat, 25 Feb 2017 04:00:28 CET
    
    libStorage
    ----------
    SemVer: 0.5.1
    OsArch: Linux-x86_64
    Branch: v0.8.1
    Commit: 35c7b6d96d5f17aa0c0379924615ae22c1ad3d45
    Formed: Sat, 25 Feb 2017 03:59:00 CET

# Bug Reports
Go panic with rbd driver with Ceph Kraken

## Expected Behavior
    rexray volume ls
lists images, like

    ID             Name       Status     Size
    rbd.test-rbs   test-rbs   available  0
    rbd.test-rbs2  test-rbs2  available  0
    rbd.testfoo    testfoo    available  0

## Actual Behavior
    [...]
    DEBU[0002] running command: [rbd ls -p rbd -l --format json]
    DEBU[0002] running command: [rbd status --pool rbd test-rbs --format json]
    DEBU[0002] task completed                                host=unix:///var/run/libstorage/656583153.sock instanceID=rbd=172.20.8.28 route=volumesForService server=nebula-piper-je service=rbd storageDriver=rbd task=0 time=1488873908773 tls=false txCR=1488873908 txID=236dd599-bc14-49dd-4b17-ccb846e8e24e
    panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
    
    goroutine 68 [running]:
    panic(0x126b7a0, 0xc420321400)
            /home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/utils.RBDHasWatchers(0xc4202d62c0,0xc4202d62a0, 0xc42024ae80, 0xc, 0x214efa0)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/utils/utils.go:339 +0xdf
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage.(*driver).toTypeVolumes(0xc4204d8a00, 0x1d898c0, 0xc42005a420, 0xc420243d80, 0x3, 0x4, 0x1, 0x0, 0xc4202a4a00, 0x0, ...)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage/rbd_storage.go:416 +0x66d
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage.(*driver).Volumes(0xc4204d8a00, 0x1d898c0, 0xc42005a420, 0xc4203788c0, 0xc42005a420, 0x4fa79f, 0xc4202a49c0, 0xc42027d630, 0x1)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage/rbd_storage.go:92 +0x103
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/registry.(*sdm).Volumes(0xc420200660, 0x1d898c0, 0xc42005a420, 0xc4203788c0, 0xc42027d640, 0x1d87c00, 0xc42027d620, 0xc42004e3ec, 0xc420142b60)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/registry/registry_storage.go:64 +0xb4
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume.getFilteredVolumes(0x1d898c0,0xc42005a420, 0xc4200be780, 0x1d87840, 0xc420320000, 0x1d82020, 0xc4202a5500, 0xc4203788c0, 0x0, 0xc42027d220, ...)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:233 +0x281
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume.(*router).volumesForService.func1(0x1d898c0, 0xc42005a420, 0x1d82020, 0xc4202a5500, 0xc42027d230, 0xc42000d9a0, 0x14813d0, 0xc)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:119 +0x80
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.execTask(0xc42029ed80)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_task.go:78 +0x732
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init.func1(0xc4202a5500)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:29 +0x73
    created by github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:31 +0xc8

## Steps To Reproduce
Upgrade ceph-common and dependencies to Ceph Kraken (from Ceph Jewel) on Debian Jessie or Ubuntu Xenial. Try to run rexray volume ls with the previously working configuration (as included below)

## Configuration Files

```yaml
#/etc/rexray/config.yml
libstorage:
  logging:
    level: debug
    httpRequests:  true
    httpResponses: true
  service: rbd
rbd:
  defaultPool: rbd
```

### Client Log
https://gist.github.com/srhb/f3bba02f50790762b6e4fbf943d6dfc4

The problem disappears immediately with a downgrade to the Jewel version of ceph-common

**Comment by akutz** [comment]
Hi @srhb,

This issue is due to a type conversion problem:

> `panic: interface conversion: interface {} is []interface {}, not map[string]interface {}`

The above error occurs because the upgrade of the underlying library (that you pinpointed) apparently caused the output that is being parsed to change. Thus when whatever Go library is responsible parses the text, it no longer is parsed as a `map[string]interface{}` but an array `[]interface{}`. 

@codenrhoden wrote the Ceph RBD driver and is the expert on it, but he's on vacation this week. I will see if @cduchesne can possibly get an environment configured for me to do some testing. Ultimately it's an issue of the way that the `rbd` tool emits its output and how that has changed. We need to:

1. Identify the new output format (if it can vary from what you already showed it to be)
2. Support the new output format
3. Retain support for the old format
4. Check the `rbd` tool version to determine which format to parse

Thank you for reporting this. We'll take care of it when time and resources permit. If you'd like to submit a PR for it sooner, please feel free!

**Comment by srhb** [comment]
Watchers used to look like this (in jewel, pre-10.2.6)

    {"watchers":{"watcher":{"address":"10.0.0.1:0\/3518311128","client":306963,"cookie":18446462598232840975}}}

And now it looks like

    {"watchers":[{"address":"10.0.0.1:0\/3518311128","client":306963,"cookie":18446462598232840975}]}

So the output fundamentally changed types in

    rbd status --pool rbd imagename --format json

**Comment by codenrhoden** [comment]
Argh, Ceph does this a lot, as a project. Though they often do introduce a flag to keep backwards compatibility. I just looked at the Kraken release notes, and there is no notice of this change. :/

We will have to start checking the version of the tool and parse appropriately. Thanks for the heads up, @srhb.

**Comment by srhb** [comment]
I agree, it's quite surprising behaviour, and it looks like it was even "backported" to the jewel 10.2.6 as well, if I recall my last tests correctly.

**Comment by codenrhoden** [comment]
@srhb I have a PR open now that I believe resolves the issue. The Ceph issue that introduced the change is http://tracker.ceph.com/issues/18261, and you are right -- the change was backporked to Jewel in 10.2.6. So I've been testing that things work in 10.2.5, 10.2.6, and 11.2.0.

How bad is this biting you? Once the PR is merged, are you able to build from source to test and move forward on your end, or will you be waiting for an official release?

**Comment by srhb** [comment]
@codenrhoden We can absolutely wait for a release, or build from source. It's a test setup, so there's no rush for us, and we're not scared of compiling anyway. :-)

Thanks for looking into this!

**Comment by ael-g** [comment]
I had the same issue as @srhb for ceph `10.2.6 (656b5b63ed7c43bd014bcafd81b001959d5f089f)`, just tested a fresh rexray build with @codenrhoden patch on libstorage and can confirm the issue has disappeared.
Thanks!
