### ISSUE TITLE
Ensure all drivers have a valid default size and reject size 0

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/libstorage#459]
@vladimirvivien commented on [Thu Aug 18 2016](https://github.com/codedellemc/rexray/issues/536)

Currently the following will work (but backend will reject request).

```
$>rexray volume create --volumename="somename"
```

Most storage backend require a size when creating a volume, the CLI probably should do the same.

---

@akutz commented on [Thu Aug 18 2016](https://github.com/codedellemc/rexray/issues/536#issuecomment-240771853)

Hi @vladimirvivien,

I would normally agree except REX-Ray and libStorage both understand and support the concept of a default size. That's why the lack of the flag is not rejected. 

---

@vladimirvivien commented on [Thu Aug 18 2016](https://github.com/codedellemc/rexray/issues/536#issuecomment-240814601)

@akutz 
I thought that was the case as well, but I just redid this test against the latest rexray without the size param and it failed.  This is using the scaleio driver.  The driver got size=0.  Should this be a bug against libStorage ?

```
$> rexray volume create --volumename="vol-test-rexray" -l debug
...
RRO[0001] error creating volume                         IOPS=0 availabilityZone= host=unix:///var/run/libstorage/282555454.sock inner=problem getting response: Wrong command parameters. You can check that you are using the correct parameters, by consulting the help for the command. instanceID=scaleio=0720519500000000 provider=scaleIO route=volumeCreate server=puzzle-pixie-sr service=scaleio size=0 task=0 time=1471482712815 tls=false txCR=1471482712 txID=995a32b1-9ec2-41c2-708d-a461f2b3ec2a volumeName=vol-test-rexray volumeType=default
```

---

@akutz commented on [Thu Aug 18 2016](https://github.com/codedellemc/rexray/issues/536#issuecomment-240818136)

I don't know. Please re-execute using all available logging. Use the tip of REX-Ray and execute the command using the embedded mode with `REXRAY_DEBUG=true` prefixed on the command line. This enables all available debug logging. It will show what is being sent and consumed between the libStorage client and server.

The config value [_is_ registered](https://github.com/emccode/libstorage/blob/master/drivers/integration/docker/docker.go#L588) with a default value of 16. I didn't write this code, and I want to refactor it anyway so that it is no longer registered as some randomly-GB value. We should support size suffixes to indicate MB or GB, etc. 

My initial thought is the bug could be in REX-Ray. If the `size` flag is not provided, the value parsed from it is 0.

---

@akutz commented on [Thu Aug 18 2016](https://github.com/codedellemc/rexray/issues/536#issuecomment-240818810)

And that's what is happening. The `size` [field](https://github.com/emccode/rexray/blob/master/rexray/cli/cli.go#L98) in REX-Ray is an `int64`, so if the value is not provided it will always be zero. We _could_ make this a pointer to an integer so it can be nil. However, I didn't write any of this code. The config value should _not_ be a string when this value is an integer. We should make the CLI value a _string_ and parse it as a size with allowed suffixes. If the string is empty, the CLI flag not set, we simply don't pass the value to libStorage instead of providing a value of 0 as we are doing now.

---

@codenrhoden commented on [Mon Feb 27 2017](https://github.com/codedellemc/rexray/issues/536#issuecomment-282882473)

Would a reasonable approach for this be to make sure that each storage driver has a default size value, built into the driver (and overridable via config).  The `linux` integration driver has a default size of 16GB, but if you don't go through the integration driver, a size 0 volume request can appear at the driver.  Some drivers reject this outright, some drivers defer to a default size, and yet still more (ahem, `rbd` gladly pass this to the backend storage).

I think having a per-driver default size might be a good idea. Several providers have minimums that must be met as well.

---

@akutz commented on [Mon Feb 27 2017](https://github.com/codedellemc/rexray/issues/536#issuecomment-282887241)

Hi @codenrhoden,

Hmmm. Maybe... Remember that REX-Ray is a client, libStorage is the API. The client, IMO, should not be important to the API to this extent. The integration driver is also client side an not at all required. For example, the client @vladimirvivien created for K8 doesn't use it.

I like your suggestion, but here's a spin on it. Just as the integration driver has defaults, perhaps what we need to introduce are defaults for the API's request parameters that a driver can elect to also override. For example:

```yaml
libstorage:
  server:
    api:
      volumes:
        create: 
          size: 10GB
  services:
    ebs-00:
      driver: ebs
    ebs-01:
      driver: ebs
      libstorage:
        server:
          api:
            volumes:
              create:
                size: 15GB
```

When the driver code requests the property `libstorage.server.api.volumes.create.size` when responding to a request issued to the `ebs-00` service, the result will be `10GB`. However, if a request is sent to the `ebs-01`, the property `libstorage.server.api.volumes.create.size` has a value of `15GB`.

These values would be defaults and only used if a request omits a property. I imagine this would be implemented at the server's router level instead of by individual drivers since, if implemented at the router level, the drivers don't have to duplicate code. It would be fairly trivial to do so in [`volume_routes.go`](https://github.com/codedellemc/libstorage/blob/master/api/server/router/volume/volume_routes.go#L380-L403), with some changes similar to the following:

```go
func (r *router) volumeCreate(
	ctx types.Context,
	w http.ResponseWriter,
	req *http.Request,
	store types.Store) error {

	service := context.MustService(ctx)

	run := func(
		ctx types.Context,
		svc types.StorageService) (interface{}, error) {

		opts := &types.VolumeCreateOpts{
			AvailabilityZone: store.GetStringPtr("availabilityZone"),
			IOPS:             store.GetInt64Ptr("iops"),
			Size:             store.GetInt64Ptr("size"),
			Type:             store.GetStringPtr("type"),
			Encrypted:        store.GetBoolPtr("encrypted"),
			EncryptionKey:    store.GetStringPtr("encryptionKey"),
			Opts:             store,
		}

		serviceConfig := r.config.Scope(
			fmt.Sprintf("libstorage.server.services.%s", service.Name())

		if opts.Size == nil {
			i := serviceConfig.GetInt(
				"libstorage.server.api.volumes.create.size")
			opts.Size = &i
		}

		v, err := svc.Driver().VolumeCreate(ctx, store.GetString("name"), opts)
```

**Comment by codenrhoden** [comment]
@akutz Reading back through this, I think perhaps I can split this into several separate issues. See if you agree:

(1) Each storage driver should have a realistic *for their storage provider* minimum size, and reject creates that are less than that. At least one driver will create size 0 volumes right now (my fault, it's RBD). If a backend doesn't have a minimum size, it should be 1GB since we only take size in GB (for now). That's the work I would like to accomplish with *this* issue. I want to fix the RBD driver (and any others I find) that push a create to the backend that zero-sized or less than we know the backend will take (GCE has a 10GB minimum, for example).

(2) Introduce API-level defaults for the size request parameters. This would allow an administrator to set different default create sizes per service, and is outlined in your [comment](https://github.com/codedellemc/rexray/issues/536#issuecomment-282887241).

(3) Update the REX-Ray CLI to use an int64 pointer (`*int64`) for holding the size param, such that if the param is not provided on the CLI, it is initialized to `nil` rather than `0`. In addition, the integration driver's [default size option](https://github.com/codedellemc/libstorage/blob/master/drivers/integration/linux/linux_gofig.go#L17) should be an int, rather than a string as it is today. If I'm not mistaken, item 2 in this list depends on 3, because we need the size param to be `nil` when not set.

If you agree, I will write up issues for 2 and 3, and target the content of (1) for the upcoming release.

**Comment by akutz** [comment]
Hi @codenrhoden,

The only issue I have with server-side defaults is, after considering them at length, I realized we have to implement them only for `POST` operations, not `PUT` as we don't want update operations that lack values to assume those missing values should be substituted with defaults. Additionally, for the CLI, I would like the size param to be a `*string` and for us to smartly parse sizes, similar to [this](https://github.com/cloudfoundry/bytefmt/blob/master/bytes.go) example.

I'd like to change the default unit for the API to bytes as it should never have been GB with which to begin. However, as you've pointed out, that would break backwards compatibility. Therefore I'd like to introduce a configurable option that lets a person specify the default unit, and have that config property default to `GB`.

Thoughts?

**Comment by codenrhoden** [comment]
@akutz. Makes sense. So, it sounds like I can take your feedback, and write up new issues for (2) and (3) slightly differently. Do you have any opposition to (1), though? I can start that immediately.

Oh, and just for fun...  where do you stand on GB vs GiB (Giga vs Gibi)?  It's something I've tried to transition to, clearly labeling things as MiB, GiB, etc when we are doing power of two. I bring it up because if we *are* going to parse sizes based on suffixes, I want to document clearly that "G" means 1024 "M", etc...

**Comment by akutz** [comment]
G or M by themselves always means base 2 IMO, thus G==GiB or 2^30 MiB. But honestly, I've also always used GB to mean base 2 as well and pretend that GB to mean 10^9 bytes doesn't exist and yell and curse HDD manufacturers loudly while I do.

-- 
-a

**Comment by codenrhoden** [comment]
@akutz One more question -- I was going to write up something to change the linux integration driver size option from a string to an int, but if we do add smart size parsing, I think we'd want to keep it as a string such that you can config a default size of `16G`. So I'm inclined to leave that alone. What do you think?

**Comment by akutz** [comment]
Well, I'm fine with the CLI being a string, but I kind of feel everything under the covers should be byte size (int64). That's problematic due to backwards-compat. Basically, my opinion is that if you're writing against code or an API you should use bytes. If you're using the CLI it can present more user friendly input options. The integration driver is client side and I'm not worried about backwards compat there, so I'd say change that to int64 for bytes. Thoughts?

**Comment by codenrhoden** [comment]
If you have a good feel for how to work that out, I totally believe you. :) I think I captured all the various pieces in issues, but I haven't written one for the integration driver. My concern there is that if someone happened to change the default value (from `16` to `10`, for example), suddenly they would start trying to create 10 byte volumes instead of 10G volumes. But I think that would be covered by your backwards-compatibility flag that treats incoming value as GB insteaed of bytes.

So I think we are good here.
