### ISSUE TITLE
Token authentication for services

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/libstorage#475]
# Summary
Token authentication for service level authentication from end-points consuming libStorage. Token in this case means a string value constituting a shared secret.

# New Feature
via @cantbewong 
An administrator that configures a libStorage server should be able to specify an authentication token for the service. This goal is that this token would uniquely be able to identify a client and also ensure authorization to perform volume operations.

Acceptance Criteria
- This feature is by default not enforced on the server side
- Must work for controller mode
- Must be a part of the libStorage API
- Must be implemented by libStorage framework

Proposal:
Configured by
- Client and Server
- Text string created by user and defined in /etc/rexray.config.yml or using other configuration mechanisms

**Comment by codenrhoden** [comment]
Personally I'm a bit confused by this one. I get creating a token per service (e.g., you need to know this string in order to use the EBS service), but how do we go about making this unique per client? This is a pre-shared secret, right? So for every client that wants to use the service, you have to create a new token for that client?

**Comment by akutz** [comment]
I updated this issue's complexity to 21 to account for the use of a signed token and the need for a CLI that generates said tokens. The documentation is complete for the server side; I'm just working on the implementation of the global and service handlers with some time lost trying to figure out how they interact with one another at the implementation level.

**Comment by akutz** [comment]
Linked to codedellemc/rexray#803
