### ISSUE TITLE
Unable to create a volume on rbd

### ISSUE THREAD

**Issue by guanjunding** [codedellemc/libstorage#486]
# Summary
I can't create volume with rexray command,but rbd command,
for example:
```sh
#rexray volume create testrbd --size=16
```

# New Feature

# Bug Reports
I found code errors about rbd driver, for example;
file 1 . github.com/codedellemc/libstorage/drivers/storage/rbd/storage/rbd_storage.go
featureLayering   = "**layering**"   

file 2. github.com/codedellemc/libstorage/drivers/storage/rbd/utils/utils.go
func RBDCreate(
	ctx types.Context,
	pool *string,
	image *string,
	sizeGB *int64,
	objectSize *string,
	features []*string) error {

	cmd := exec.Command(
		rbdCmd, "create", poolOpt, *pool,
		"--object-size", *objectSize,
		"--size", strconv.FormatInt(*sizeGB, 10)+"G",
	)

	for _, feature := range features {
		cmd.Args = append(cmd.Args, "--image-feature")
		cmd.Args = append(cmd.Args, *feature)
	}
        ...

but when I  rbd create -h command,I found that:
Other input options:
  -p, --pool <pool>                  source pool name
  --image <image-name>               image name
  --dest <image-name>                destination [pool and] image name
  --snap <snap-name>                 snapshot name
  --dest-pool <name>                 destination pool name
  --path <path-name>                 path name for import/export
  --size <size in MB>                size of image for create and resize
  --order <bits>                     the object size in bits; object size will be
                                     (1 << order) bytes. Default is 22 (4 MB).
  --image-format <format-number>     format to use when creating an image
                                     format 1 is the original format (default)
                                     format 2 supports cloning
  --image-features <features>        optional format 2 features to enable
                                     +1 layering support, +2 striping v2,
                                     +4 exclusive lock, +8 object map

On the whole, I think should update layering to +1 or , update  "object-size" to "order" ro remove it, and remove "G" from "--size", strconv.FormatInt(*sizeGB, 10)+"G" options;

## Expected Behavior
volume created

## Actual Behavior
FATA[0000] error creating volume        error.status=500 volume=testrbd

## Configuration Files
`/etc/rexray/config.yml`
```yaml
rexray:
  logLevel: debug
libstorage:
  service: rbd
  integration:
    volume:
      operations:
        create:
          default:
            size: 20
rbd:
  defaultPool: rbd
```
###logs
### Service Log
time="2017-03-27T09:43:17+08:00" level=debug msg="running command: [rbd info -p rbd testrbd --format json]" 
time="2017-03-27T09:43:17+08:00" level=debug msg="running command: [rbd create --pool rbd --object-size 4M --size 16G --image-feature layering testrbd]" 
time="2017-03-27T09:43:17+08:00" level=error msg="Unable to create RBD: " 
time="2017-03-27T09:43:17+08:00" level=error msg="Failed to create new volume" host="unix:///var/run/libstorage/498381072.sock" instanceID="rbd=180.163.255.162" route=volumeCreate server=brass-raccoon-sl service=rbd storageDriver=rbd task=0 time=1490578997373 tls=false txCR=1490578997 txID=0372e2c7-1b57-431c-78ce-6b8c17af467c 
time="2017-03-27T09:43:17+08:00" level=debug msg="task completed" host="unix:///var/run/libstorage/498381072.sock" instanceID="rbd=180.163.255.162" route=volumeCreate server=brass-raccoon-sl service=rbd storageDriver=rbd task=0 time=1490578997373 tls=false txCR=1490578997 txID=0372e2c7-1b57-431c-78ce-6b8c17af467c 
time="2017-03-27T09:43:17+08:00" level=error msg="Failed to create new volume" host="unix:///var/run/libstorage/498381072.sock" route=volumeCreate server=brass-raccoon-sl time=1490578997373 tls=false txCR=1490578997 txID=0372e2c7-1b57-431c-78ce-6b8c17af467c 

### Client Log
FATA[0000] error creating volume                         error.status=500 volume=testrbd

Thank you for your reply!!!

**Comment by codenrhoden** [comment]
Hello @guanjunding. What version of Ceph are you using? The `rbd create` command the `rbd` driver issues is correct, but uses features of the `rbd` CLI that are only available as of the Ceph **Jewel** release (10.x). That was as far back as we were willing to go with the driver.

It is likely (and my fault) that this is not called out clearly in the docs.

**Comment by guanjunding** [comment]
Thanks for your reply, I tested it with the version of Ceph is Hammer,  I should test the version Jewel, and then reply the result. Thank you @codenrhoden

**Comment by guanjunding** [comment]
hello @codenrhoden , I hava tested wiht rbd Cli version 10.2.6, And It's work well.
# rpm -qa  | grep ceph-common
ceph-common-10.2.6-0.el7.x86_64
# rexray volume create testrbd --size=16
# rbd ls
testrbd
Thank you @codenrhoden

**Comment by codenrhoden** [comment]
Great! Glad you got it working, @guanjunding
