### ISSUE TITLE
Can't find aws credentials

### ISSUE THREAD

**Issue by jonathan-kosgei** [codedellemc/libstorage#505]
# Summary
Creating an ebs volume fails with the error NoCredentialProviders: no valid providers in chain even though I have working keys in the `~/.aws/credentials` file

## Expected Behavior
Should be able to read the creds

## Actual Behavior
```
root@ip-172-31-25-54:~# docker volume create --driver=ebs --name=example-ebs
Error response from daemon: create example-ebs: VolumeDriver.Create: {"Error":"error getting volume"}
```

**Comment by akutz** [comment]
Hi @jonathan-kosgei,

We appreciate you submitting the issue and would also very much like if you would adhere to the guidelines for doing so, including attaching debug logs via a Gist. 

Per the EBS driver's [documentation](http://libstorage.readthedocs.io/en/stable/user-guide/storage-providers/#elastic-block-storage) it *should* support AWS SDK native means of storing credentials, but I wonder if there's a bug? 

The only other idea off the top of my head is whether your credentials are stored in your home directory or the root user's home directory as REX-Ray would be running as root.

**Comment by akutz** [comment]
Hi @jonathan-kosgei,

After reviewing the [pertinent](https://github.com/codedellemc/libstorage/blob/master/drivers/storage/ebs/storage/ebs_storage.go#L74-L189) sources I'm inclined to think this is a bug FWIW. I believe the AWS SDK *would* do the right thing if we weren't insisting that credentials should be derived from our configuration or the client.

**Comment by akutz** [comment]
Hi @jonathan-kosgei,

May I ask why you closed this? FWIW I did some more digging and noted that the EBS driver *does* in fact refer to the environment variable and credential file provider if they're present:

```go
			Credentials: credentials.NewChainCredentials(
				[]credentials.Provider{
					&credentials.StaticProvider{
						Value: credentials.Value{
							AccessKeyID:     akey,
							SecretAccessKey: skey,
						},
					},
					&credentials.EnvProvider{},
					&credentials.SharedCredentialsProvider{},
					&ec2rolecreds.EC2RoleProvider{
						Client: ec2metadata.New(sess),
					},
				},
			),
```

Thus it *should* work for you. I'm curious as to why you closed the issue with no comment?
