### ISSUE TITLE
Add storage driver option to inspect volume by name

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/libstorage#560]
# Summary
I propose to add an optional enhancement to storage drivers, where they can add a `VolumeInspectByName` method that can quickly lookup a single volume on the backend for providers that support looking up a volume by name instead of ID.

# New Feature
There are several motivating factors for this one, so hear me out.

Right now, the storage drivers have `Volumes` and `VolumeInspect` methods. The former returns all volumes it can find on the backend, and the latter returns a single volume, as referenced by it's `volumeID`. For every method that acts on an existing volume, the storage drivers expect a `volumeID` as their unique identifier to the volume in question. When creating a new volume, a name is required, and the `volumeID` is figured out after the volume exists.

From a libStorage client perspective, we see that we spend significant effort figuring out what the right `volumeID` is, because in practice we are usually given a `name` instead of `volumeID`. REX-Ray goes to great lengths to make sure that you can reference a volume by either an ID or a name.

As currently implemented, I think we are wasting a lot of cycles on this. Many of the storage providers allow an API query to "get" a volume by name. What we are doing now is that whenever we need to find the `volumeID`, we first call to `Volumes()`, getting  a list of all volumes, then do a string match on the name to find the right volume. Then we can use the associated `volumeID` for subsequent actions like `attach`, `detach`, etc.  We can see this in REX-Ray's CLI, where something like `rm` first [does an ls](https://github.com/codedellemc/rexray/blob/master/cli/cli/cmds_10_volume.go#L235) to get all volumes and matches the name, then [removes based on the ID](https://github.com/codedellemc/rexray/blob/master/cli/cli/cmds_10_volume.go#L264).

I think it would be better if these methods instead used a `VolumeInspect`, to get the one and only matching Volume. But today, that is not possible because users usually pass in the volume name, not the ID. Furthermore, the Docker volume driver *only* uses names -- it never looks at IDs. Which is why the integration driver [duplicates](https://github.com/codedellemc/libstorage/blob/master/drivers/integration/linux/linux.go#L132-L139) this "volume ls, match on name to get ID" logic that the REX-Ray CLI uses. I realize that REX-Ray has a pattern matching system in place that requires on the `ls` functionality, and I think that can be maintained. I can go into more detail on that later in a REX-Ray issue if we get that far.

I think we can be a lot more efficient by supporting a `VolumeInspect` method in libStorage storage services that accepts a volume name instead of an ID. The libStorage framework actually has a way to do this "match by name" all on the server side today, by setting the `byName` querystring for `VolumeInspect`, as seen [here](https://github.com/codedellemc/libstorage/blob/master/api/server/router/volume/volume_routes.go#L301-L338). This is an improvement in that it vastly reduces the amount of data transferred back to the caller down to just the matching volume instead of potentially dozens or hundreds, but it is still a heavier call than may be required for many storage providers.

My last reason for wanting this feature is to solve #450 and #458, where we want to automatically replace underscores in a volume name to dashes. It is trivial to do this upon volume creation, but after that point the volume is essentially unaccessible unless you are using volume IDs.  If Docker creates a volume named `test_test`, for example, and then we create `test-test` on the backend, we will always report the volume's name as `test-test` in the future. We can **not transform the volume name back** to `test_test` in queries, as this runs the danger of modifying names that were originally created with dashes on purpose. If there was a `VolumeInspectByName` function for the driver, it could take the name `test_test` and transform it to `test-test` and find the right volume, at which point the caller would have the correct `volumeID`. Without such a function, there is no way for a libStorage client to lookup such a volume by name.

# Proposal
I suggest we add a new interface, something like `StorageDriverWithNameInspect`, and when a `VolumeInspect` request comes into the volume router, we check if the storage driver implements that interface and use it in the `byName` [case](https://github.com/codedellemc/libstorage/blob/master/api/server/router/volume/volume_routes.go#L301-L338) instead of the current methodology. We fall back to the current stuff if the driver doesn't support it.

With that enhancement in place, we then modify the integration driver to use the `byName` flag in combination with `VolumeInspect` instead of the [current `Inspect`](https://github.com/codedellemc/libstorage/blob/master/drivers/integration/linux/linux.go#L132-L139) approach. Keep in mind this already accepts a *name*, not an ID. We would also enhance the `volumeInspectByIDOrName` [logic](https://github.com/codedellemc/libstorage/blob/master/drivers/integration/linux/linux_utils.go#L56-L71) to be more efficient in the "or name" case.

And finally, the end game would be to enhance the REX-Ray CLI to use `VolumeInspect` more appropriately. If this proposal is acted upon, a separate issue would cover the REX-Ray side of things, but I think there are several improvements that can be made there as well. No point in discussing them at length here, as it is all moot unless this libStorage proposal makes sense.

**Comment by akutz** [comment]
LGTM. I'll add an interface and update the Framework logic. I'm going to assert that from an API perspective we leave it as a VolumeInspectRequest and simply route it to the appropriate function depending on whether or not the driver implements the new interface.

**Comment by akutz** [comment]
Hi @codenrhoden,

So I started to add this and push a Framework change when I encountered what will make this a chore. We should still do it, but let's sit down tomorrow and discuss how we handle these one-offs in the [registry](https://github.com/codedellemc/libstorage/blob/master/api/registry/registry_storage.go). Because I already maintain two separate storage driver wrappers: one for the vanilla driver and one for the driver with the `Login` function. An additional interface would mean we'd need the registry to define four variants of a storage driver:

1. storage driver
2. storage driver with login
3. storage driver with volume inspect by name
4. storage driver with volume inspect by name with login

I don't mind doing this, but I also think at some point, maybe now, we should figure out if there is a better approach than the one I've used. This is only an issue due to the fact that we wrap all drivers with registry-specific proxies. It enables us to inject the driver instances prior to them being available.

**Comment by codenrhoden** [comment]
@akutz Cool! Well, cool that you think it is a good idea. I wasn't expecting you to jump right on it -- and thought maybe it was something I could tackle. But I don't know the registry side of things very well at all. Let me take some time to read through that code again, and then we can chat later today. I agree that solving the problem you outlined now would be best, because we don't want the variants to grow exponentially if we add others.

**Comment by akutz** [comment]
Hi @codenrhoden,

I got this far with it before I realized the challenge the registry presents:

```diff
$ git stash show --patch stash@{0}
diff --git a/api/registry/registry_storage.go b/api/registry/registry_storage.go
index 997c0a6..b713c7b 100644
--- a/api/registry/registry_storage.go
+++ b/api/registry/registry_storage.go
@@ -12,6 +12,12 @@ type sdmWithLogin struct {
        types.Context
 }
 
+type sdmWithVolInspectByName struct {
+       types.StorageDriver
+       types.StorageDriverVolInspectByName
+       types.Context
+}
+
 // NewStorageDriverManager returns a new storage driver manager.
 func NewStorageDriverManager(
        d types.StorageDriver) types.StorageDriver {
diff --git a/api/types/types_drivers_storage.go b/api/types/types_drivers_storage.go
index 5e7f0ce..cf34575 100644
--- a/api/types/types_drivers_storage.go
+++ b/api/types/types_drivers_storage.go
@@ -366,6 +366,17 @@ type StorageDriver interface {
                opts Store) error
 }
 
+// StorageDriverVolInspectByName is an interface for storage drivers that
+// implement the VolumeInspectByName function.
+type StorageDriverVolInspectByName interface {
+
+       // VolumeInspectByName inspects a single volume by name.
+       VolumeInspectByName(
+               ctx Context,
+               volumeName string,
+               opts *VolumeInspectOpts) (*Volume, error)
+}
+
 // StorageDriverWithLogin is a StorageDriver with a Login function.
 type StorageDriverWithLogin interface {
        StorageDriver
```

I'm more than fine with you handling this. I wasn't trying to prevent that; more just trying to quickly provide a solution for someone :) But sure, once we figure this out, you should definitely take care of it.

**Comment by codenrhoden** [comment]
@akutz 

Okay, I tried to familiarize myself with the registry anew, and I think I understand how it's all working. I see that the registry-specific proxy is there, and that it is actually this proxy that gets pulled out of the context when making calls to Drivers, and this proxy then, ahem, proxies the call to the actual driver.

I'm wondering, though, if there is a need for the all the different proxies at all. Right now we have one specific case, the `Login` addition, that is handled differently. But the one and only place where Login [is called] by the context does a type assertion first to make sure that that method is actually there. What if we make that a requirement, and find a way to do type assertions on the driver **in the driver manager struct** instead of the struct itself, something like the following (doesn't compile, as it would change a lot of things):


```diff
 type sdm struct {
-       types.StorageDriver
+       Driver types.StorageDriver
        types.Context
 }

-type sdmWithLogin struct {
-       types.StorageDriverWithLogin
-       types.Context
-}
+//type sdmWithLogin struct {
+//     types.StorageDriverWithLogin
+//     types.Context
+//}

 // NewStorageDriverManager returns a new storage driver manager.
 func NewStorageDriverManager(
        d types.StorageDriver) types.StorageDriver {
-       return &sdm{StorageDriver: d}
+       return &sdm{Driver: d}
 }
```

We then would have the context package return the `driver` value instead of the `sdm` struct, though that probably doesn't work because we lose the Context then... but I feel like there is a way to peek into the underlying driver itself, and type assert on that instead of the `sdm` struct. And at the point, I wonder if we can get rid of the proxy altogether (meaning, not define `(d *sdm)` methods, and instead have the context return `sdm.Driver` and let those methods be called directly...

I'm not real sure I know what I'm talking about here. It would be more of a trial and error thing to see if I could figure it out, as my go interface-fu is not that strong.

**Comment by akutz** [comment]
Hi @codenrhoden,

This is all very much like how the executor determines what is supported. I see two paths forward:

1. Either all Drivers must define a function `Type() interface{}` that returns the actual object on which to do the type assertion.
2. Or all Drivers must define a function `Supported() int64` that returns a mask of the functions the driver supports. It could also be `Supported() []string` to return names of functions, but I like the mask better myself.

Thoughts?
