### ISSUE TITLE
Support out-of-tree storage drivers

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#566]
# Summary
The ability to support out-of-tree storage drivers is an oft-requested feature. This enhancement will make it easier for developers to add new support to libStorage without having to be a member of this repository of the libStorage CI pipeline.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #969](https://github.com/codedellemc/rexray/issues/969) via [**ZenHub**](https://www.zenhub.com/)
