### ISSUE TITLE
Support multiple endpoint providers

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#567]
# Summary
Currently the libStorage server implementation supports a single endpoint provider: the libStorage API HTTP/REST provider. This issue tracks the required changes to support multiple endpoint providers, such as a [CSI](https://github.com/container-storage-interface/spec/blob/master/spec.md) endpoint provider or a [Docker Volume Driver](https://docs.docker.com/engine/extend/plugins_volume/) endpoint provider.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #970](https://github.com/codedellemc/rexray/issues/970) via [**ZenHub**](https://www.zenhub.com/)
