### ISSUE TITLE
Multiple hosts sharing a mount point

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#60]
Today the drivers have all been built to ensure that only a single host has access to a volume at any one point in time. In the future with more drivers and filesystems, it would be relevant to ensure that it is possible to use libStorage in the use cases where there is a single volume that can be attached by multiple hosts.

This could be something that is more explicitly defined via the storage driver interface.

**Comment by clintonskitson** [comment]
This was introduced for the Isilon driver using the existing `preemption` and new driver specific `sharedMount` flag.

**Comment by clintonskitson** [comment]
This logic should be expanded to cover block devices as well and done at a global level. This feature has a lot of dependent changes including device formatting, and FS support beyond (XFS/EXT4). More use cases are needed here.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/rexray #941](https://github.com/codedellemc/rexray/issues/941) via [**ZenHub**](https://www.zenhub.com/)
