### ISSUE TITLE
Storage pools as first class

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#61]
Today the volumeType is implicit in nature where by specifying any volumeType, it is up to the storage platform to accept/reject the volume creation. Having this be more explicit where a lookup of available store types may be a good addition to the functionality.

**Comment by codenrhoden** [comment]
I presume this would be something up to storage driver -- if they can, query the provider for available types/pools/etc. The follow-up question is: is this then just used to reject a request for an invalid type sooner? Or is it an enhancement to the framework to be able to query available types?
