### ISSUE TITLE
Storage arrays as first class

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#62]
Tied to https://github.com/emccode/libstorage/issues/58

As services usage expands, it would be great to include storage arrays as first class. I can see a few different valid reasons for this.

1) Locking - Having a single object as a storage platform means that libStorage could enable some form of locking to the resource. This might be useful to ensure 'idempotent' operations where multiple libStorage clients are requesting the same resource at the same time. For example, today the EC2 drive if invoked from multiple locations will create multiple volumes with the same name due to how the volume gets created. Also if implementing quotas at some point, this would help as well. Having a single location that can perform blocking for certain types of operations would help satisify this. 
2) Simpler configuration - Not repeating the platform configuration would make things cleaner for larger configurations. The recursive lookup from gofig works today only if one platform is configured at root to inheret those settings to services. Having the storage array as the object seems to be the right solution here.
3) Friendly when adding services since not duplicating creds - Having a service from outside of libStorage need to repeatly add the creds of a platform after the initial service has been configured may not be ideal.

Plenty of design work to do. On the driver side the array identifier is a major change across the drivers to make this happen.

**Comment by codenrhoden** [comment]
I'm not sure that most of this applies anymore...

> For example, today the EC2 drive if invoked from multiple locations will create multiple volumes with the same name due to how the volume gets created

The requests into the drivers are serial -- I don't think this is true. The drivers first see if a volume already exists.

As for points 2 and 3, I think there are multiple ways in the YAML file to only list certain details once, especially credentials.

I'm going to close this for now -- reopen if in disagreement.
