### ISSUE TITLE
Authenticating clients against individual services

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#63]
It would be great to have a libS client to be able to authenticate via SSL as an authorized user of a service. Alternatively an authentication token within established SSL certs that are shared across services could also work here. This would pertain to a libStorage client talking to possibly many services as well.

Lots of work here to be done here.

**Comment by codenrhoden** [comment]
Related to https://github.com/codedellemc/rexray/issues/584

**Comment by codenrhoden** [comment]
From @vladimirvivien 

- Users should be able to securely connect the libStorage client to the libStorage server
  - authenticate per service an option
- A user should have the ability to easily configure a secure connection between libStorage client and the service backend
- Users should be able to configure secured connection using several configuration vectors including environment variables and the client configuration YAML file.

**Comment by codenrhoden** [comment]
Token auth tracked via #475

**Comment by akutz** [comment]
Replaced by #475.
