### ISSUE TITLE
Global, region, availability zone based awareness of requests to server

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#65]
Some users may require regional data center awareness. If libStorage server is the single interface for storage for all regions, then it needs awareness of how to properly handle requests. If someone requests services for a certain instance then only the available storage platforms to that instance should be available.

Is this functionality of libStorage or the implementor of libStorage, ie. Polly?

Today the libStorage service abstraction model does not implement logic relating to advertising or not advertising services. This means that the deployment of libStorage would be done per region or availability zone.

Is a model where libStorage instances are talking with another and there is a central libStorage instance going to help here?

**Comment by codenrhoden** [comment]
I wonder if this is taken care of by what we've done with Instance IDs. libStorage clients send their IID header, which can contain details of their region/AZ (if available/appropriate). This allows a centralized libStorage server to make sure it sends requests to the right endpoint for the region.

Going close based on that info. reopen if needed.
